name: Integration tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  ts-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          # Use hubbleprotocolbot's key:
          # - docker+cargo fails when mounting multiple keys (https://github.com/docker/buildx/issues/341)
          # - GitHub does not support reusing deploy keys
          ssh-private-key: |
            ${{ secrets.HUBBLEPROTOCOLBOT_GITHUB_KEY }}
      - uses: actions/checkout@v3
      - uses: hubbleprotocol/solana-setup-action@v0.1
        with:
          solana-version: v1.14.15
          rust-version: stable
          anchor-version: v0.26.0
          setup-node: 19

      - name: build programs
        run: |
          make build
      - name: test
        run: |
          make test-validator > validator.logs 2>&1 &
          sleep 15
          make airdrop
          make deploy
          make test-ts
